[character]
name = "Sam Sottofrasca"
classe = "Ladro"
livello = "5"
razza = "halfling"
background = "Investigatore"
allineamento = "Caotico Neutrale"
nome_giocatore = "Raffa"
punti_esperienza = "1058"
